import type { Bb } from "./client.js";
import { unwrap, unwrapMaybe } from "./client.js";
import { insertReturning } from "./upsert.js";

/**
 * Panel persistence — the durable seam that lets a panel generated by the
 * iMessage worker be re-opened as a real web page (`/panel/[id]`).
 *
 * The worker can't host the interactive HTML panel inside an iMessage bubble,
 * so instead it SAVES the grounding data (brand + ranked influencers) to the
 * `panels` table and texts a link. The web route reads the row back and
 * regenerates the exact same panel on demand. Storing the *spec* (not the
 * rendered HTML) keeps the row tiny and lets the panel design evolve without
 * rewriting history.
 */

/** The grounding bundle we persist in `panels.spec` and re-hydrate on read. */
export interface PanelSpec {
  brand?: string;
  brandUrl?: string;
  influencers: PanelInfluencer[];
}

export interface PanelInfluencer {
  handle: string;
  platform: string;
  pk?: string;
  followers?: number;
  score?: number;
  rationale: string;
}

export interface SavedPanel {
  id: string;
  title: string | null;
  spec: PanelSpec;
}

/** The placeholder owner used across the demo's seed data (no real auth). */
const DEMO_OWNER = "00000000-0000-0000-0000-000000000000";
/** A dedicated store that messaging-originated panels hang off of. */
const MESSAGING_STORE_SLUG = "imessage-demo";

/**
 * Find-or-create the store that iMessage panels attach to. `panels.store_id`
 * is a NOT-NULL FK, but the worker has no store context, so we keep one stable
 * "store" for this channel and reuse it. Idempotent: safe to call per message.
 */
export async function ensureMessagingStore(bb: Bb): Promise<string> {
  const found = unwrapMaybe(
    await bb.from("stores").select("id").eq("slug", MESSAGING_STORE_SLUG).maybeSingle(),
  ) as { id?: string } | null;
  if (found?.id) return found.id;

  const created = await insertReturning<{ id: string }>(bb, "stores", {
    owner_id: DEMO_OWNER,
    name: "iMessage",
    slug: MESSAGING_STORE_SLUG,
  });
  return created.id;
}

/**
 * Persist a panel's grounding spec and return its id. The id becomes the
 * `/panel/[id]` URL the marketer taps from their phone.
 */
export async function savePanel(
  bb: Bb,
  input: { title?: string; storeId: string; spec: PanelSpec; source?: string },
): Promise<string> {
  const row = await insertReturning<{ id: string }>(bb, "panels", {
    store_id: input.storeId,
    title: input.title ?? null,
    format: "html",
    source: input.source ?? "imessage",
    spec: input.spec,
    status: "ready",
  });
  return row.id;
}

/** Read a saved panel back by id. Returns null when it doesn't exist. */
export async function loadPanel(bb: Bb, id: string): Promise<SavedPanel | null> {
  const row = unwrapMaybe(
    await bb.from("panels").select("id,title,spec").eq("id", id).maybeSingle(),
  ) as { id: string; title: string | null; spec: PanelSpec } | null;
  if (!row) return null;
  return { id: row.id, title: row.title, spec: row.spec ?? { influencers: [] } };
}
